import jwt from "jsonwebtoken";

export const generateToken = (user) => {
    return jwt.sign(
        { id: user._id, role: user.role },  // id: unique id generated by MongoDB, role: user role
        process.env.JWT_SECRET,     // secret key for signing the token
        { expiresIn: "1d" }     // token valid for 7 days
    );
};